name: scCotag
channels:
  - pytorch
  - nvidia
  - anaconda
  - torch
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - anndata=0.11.4=pyhd8ed1ab_0
  - aom=3.3.0=h27087fc_1
  - array-api-compat=1.12.0=pyhe01879c_0
  - asttokens=3.0.0=py312h06a4308_0
  - blas=1.0=mkl
  - brotli=1.1.0=hb9d3cd8_2
  - brotli-bin=1.1.0=hb9d3cd8_2
  - brotli-python=1.0.9=py312h6a678d5_9
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.8.3=hbd8a1cb_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.1=py312h06a4308_0
  - contourpy=1.3.2=py312h68727a3_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.1=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.9.19=0
  - cuda-runtime=12.4.1=0
  - cuda-version=12.9=3
  - cycler=0.12.1=pyhd8ed1ab_1
  - debugpy=1.8.11=py312h6a678d5_0
  - decorator=5.1.1=pyhd3eb1b0_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=0.8.3=pyhd3eb1b0_0
  - expat=2.7.0=h5888daf_0
  - ffmpeg=4.4.1=h964e5f1_4
  - fonttools=4.58.1=py312h178313f_0
  - freetype=2.13.3=ha770c72_1
  - giflib=5.2.2=h5eee18b_0
  - gmp=6.3.0=h6a678d5_0
  - gmpy2=2.2.1=py312h5eee18b_0
  - gnutls=3.6.15=he1e5248_0
  - h5py=3.13.0=nompi_py312h01d377b_101
  - hdf5=1.14.6=nompi_h2d575fe_101
  - importlib-metadata=8.7.0=pyhe01879c_1
  - intel-openmp=2022.0.1=h06a4308_3633
  - ipykernel=6.29.5=py312h06a4308_1
  - ipython=9.1.0=py312h06a4308_0
  - ipython_pygments_lexers=1.1.1=py312h06a4308_0
  - jedi=0.19.2=py312h06a4308_0
  - joblib=1.5.1=pyhd8ed1ab_0
  - jsonschema=4.23.0=py312h06a4308_0
  - jsonschema-specifications=2023.7.1=py312h06a4308_0
  - jupyter_client=8.6.3=py312h06a4308_0
  - jupyter_core=5.7.2=py312h06a4308_0
  - kiwisolver=1.4.8=py312h84d6215_0
  - krb5=1.21.3=h143b758_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.17=h717163a_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - legacy-api-wrap=1.4.1=pyhd8ed1ab_0
  - lerc=4.0.0=h0aef613_1
  - libaec=1.1.3=h6a678d5_0
  - libblas=3.9.0=16_linux64_mkl
  - libbrotlicommon=1.1.0=hb9d3cd8_2
  - libbrotlidec=1.1.0=hb9d3cd8_2
  - libbrotlienc=1.1.0=hb9d3cd8_2
  - libcblas=3.9.0=16_linux64_mkl
  - libcublas=12.4.5.8=0
  - libcufft=11.2.1.3=0
  - libcufile=1.14.0.30=4
  - libcurand=10.3.10.19=0
  - libcurl=8.14.0=h332b0f4_0
  - libcusolver=11.6.1.9=0
  - libcusparse=12.3.1.170=0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libev=4.33=hd590300_2
  - libexpat=2.7.0=h5888daf_0
  - libffi=3.4.4=h6a678d5_1
  - libfreetype=2.13.3=ha770c72_1
  - libfreetype6=2.13.3=h48d6fc4_1
  - libgcc=15.1.0=h767d61c_2
  - libgcc-ng=15.1.0=h69a702a_2
  - libgfortran=15.1.0=h69a702a_2
  - libgfortran5=15.1.0=hcea5267_2
  - libgomp=15.1.0=h767d61c_2
  - libhwloc=2.11.2=default_h0d58e46_1001
  - libiconv=1.18=h4ce23a2_1
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblapack=3.9.0=16_linux64_mkl
  - libnghttp2=1.64.0=h161d5f1_0
  - libnpp=12.2.5.30=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.9.19=0
  - libnvjitlink=12.4.127=0
  - libnvjpeg=12.3.1.117=0
  - libopenblas=0.3.29=pthreads_h94d23a6_0
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.47=h943b412_0
  - libsodium=1.0.18=h7b6447c_0
  - libsqlite=3.45.2=h2797004_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_2
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.7.0=he137b08_1
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libva=2.21.0=h4ab18f5_1
  - libvpx=1.11.0=h295c915_0
  - libwebp=1.5.0=hae8dbeb_0
  - libwebp-base=1.5.0=h851e524_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxml2=2.13.5=h064dc61_0
  - libzlib=1.3.1=hb9d3cd8_2
  - llvm-openmp=15.0.7=h0cdce71_0
  - llvmlite=0.44.0=py312h374181b_1
  - matplotlib-base=3.10.3=py312hd3ec401_0
  - matplotlib-inline=0.1.6=py312h06a4308_0
  - mkl=2022.1.0=hc2b9512_224
  - mpc=1.3.1=h5eee18b_0
  - mpfr=4.2.1=h5eee18b_0
  - munkres=1.1.4=pyh9f0ad1d_0
  - narwhals=1.31.0=py312h06a4308_1
  - natsort=8.4.0=pyh29332c3_1
  - nbformat=5.10.4=py312h06a4308_0
  - ncls=0.0.70=py312h0fa9677_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=py312h06a4308_0
  - nettle=3.7.3=hbbd107a_1
  - numba=0.61.2=py312h2e6246c_0
  - ocl-icd=2.3.2=h5eee18b_1
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.3=h5fbd93e_0
  - openssl=3.5.2=h26f9b46_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.2.3=py312hf9745cd_3
  - parso=0.8.4=py312h06a4308_0
  - patsy=1.0.1=pyhd8ed1ab_1
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pillow=11.2.1=py312h80c1187_0
  - pip=25.1=pyhc872135_2
  - platformdirs=4.3.7=py312h06a4308_0
  - plotly=6.0.1=py312he3bba80_0
  - pot=0.9.5=py312hf9745cd_0
  - prompt-toolkit=3.0.43=py312h06a4308_0
  - prompt_toolkit=3.0.43=hd3eb1b0_0
  - pthread-stubs=0.4=hb9d3cd8_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pygments=2.19.1=py312h06a4308_0
  - pynndescent=0.5.13=pyhd8ed1ab_1
  - pyparsing=3.2.3=pyhd8ed1ab_1
  - pyranges=0.1.4=pyhdfd78af_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0.post0=pyhff2d567_1
  - python-fastjsonschema=2.20.0=py312h06a4308_0
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.12=7_cp312
  - pytorch=2.5.1=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_7
  - pytorch-mutex=1.0=cuda
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py312h5eee18b_0
  - pyzmq=26.2.0=py312h6a678d5_0
  - qhull=2020.2=h4bd325d_2
  - readline=8.2=h5eee18b_0
  - referencing=0.30.2=py312h06a4308_0
  - rpds-py=0.22.3=py312h4aa5aa6_0
  - scanpy=1.11.1=pyhd8ed1ab_0
  - scikit-learn=1.5.2=py312h7a48858_1
  - scikit-misc=0.5.1=py312h6a55c13_3
  - scipy=1.15.2=py312ha707e6e_0
  - seaborn=0.13.2=hd8ed1ab_3
  - seaborn-base=0.13.2=pyhd8ed1ab_3
  - session-info2=0.1.2=pyhd8ed1ab_0
  - setuptools=78.1.1=py312h06a4308_0
  - shap=0.48.0=cpu_py312hc6e6151_0
  - six=1.17.0=pyhd8ed1ab_0
  - slicer=0.0.8=pyhd8ed1ab_0
  - sorted_nearest=0.0.39=py312h0fa9677_6
  - sqlite=3.45.2=h2c6b66d_0
  - stack_data=0.2.0=pyhd3eb1b0_0
  - statsmodels=0.14.4=py312hc0a28a1_0
  - svt-av1=1.1.0=h27087fc_1
  - tabulate=0.9.0=pyhd8ed1ab_2
  - tbb=2022.1.0=h4ce085d_0
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_hd72426e_102
  - torchtriton=3.1.0=py312
  - tornado=6.5=py312h5eee18b_0
  - traitlets=5.14.3=py312h06a4308_0
  - typing_extensions=4.13.2=pyh29332c3_0
  - tzdata=2025b=h04d1e81_0
  - umap-learn=0.5.7=py312h7900ff3_1
  - unicodedata2=16.0.0=py312h66e93f0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - wheel=0.45.1=py312h06a4308_0
  - x264=1!161.3030=h7f98852_1
  - x265=3.5=h924138e_3
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=hb9d3cd8_0
  - xorg-libxdmcp=1.1.5=hb9d3cd8_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - aiohappyeyeballs==2.6.1+computecanada
      - aiohttp==3.11.14+computecanada
      - aiosignal==1.3.2+computecanada
      - attrs==25.3.0+computecanada
      - charset-normalizer==3.4.2
      - et-xmlfile==2.0.0
      - filelock==3.18.0+computecanada
      - frozenlist==1.6.0
      - fsspec==2025.5.1+computecanada
      - geomloss==0.2.6+computecanada
      - idna==3.10+computecanada
      - igraph==0.11.9
      - jinja2==3.1.6+computecanada
      - keopscore==2.3
      - markupsafe==2.1.5+computecanada
      - mpmath==1.3.0+computecanada
      - multidict==6.4.4
      - networkx==3.5
      - numpy==2.2.2+computecanada
      - openpyxl==3.1.5
      - pillow-simd==9.5.0.post2+computecanada
      - propcache==0.3.1+computecanada
      - psutil==6.1.1+computecanada
      - pybind11==3.0.1
      - pykeops==2.3
      - requests==2.32.3+computecanada
      - sympy==1.13.1+computecanada
      - texttable==1.7.0
      - torch==2.6.0+computecanada
      - torch-geometric==2.6.1+computecanada
      - torchaudio==2.6.0+computecanada
      - torchvision==0.21.0+computecanada
      - tqdm==4.67.1+computecanada
      - typing-extensions==4.13.2+computecanada
      - urllib3==2.4.0+computecanada
      - yarl==1.20.0
prefix: /home/liy110/anaconda3/envs/biocuda
